### ISSUE TITLE
Proposal to add TODO test result with yellow color tag

### ISSUE THREAD

**Issue by softael** [sheredom/utest.h#100]
**Why?**
When writing tests it is common to put some unimportant function aside due to low-priority in order to implement tests later. It is a very dangerous practice, because you might think that the whole module is tested, but it is not always the case and some functions might be left out for later and eventually forgotten. It would be really nice if framework would allow to call UTEST_TODO() to mark test as unimplemented which would show it as yellow in the summary.

One can argue you should use test coverage utils but lets be honest it is rarely the case.

**How?**
Add another result OK, FAILED, TODO with yellow color marker.

**Who?**
I can do it if you are willing to assist along the way to eventually PR it (so no-ones time is wasted). But if it is an easy feature I would rather let other people familiar with the library do it.

**Unrelated Notes**
Very nice library. The fact that tests are auto-added is a game changer. Have a great day!

**Comment by sheredom** [comment]
Wow - GitHub's notifcations are so bad I completely missed this one sorry.

That seems a) useful and b) easy to implement, I'll give it a whirl and report back!

**Comment by sheredom** [comment]
@softael - wondering whether it should be `UTEST_SKIP` to match what GTEST does? 🤔 https://google.github.io/googletest/advanced.html#skipping-test-execution

**Comment by softael** [comment]
> @softael - wondering whether it should be `UTEST_SKIP` to match what GTEST does? 🤔 https://google.github.io/googletest/advanced.html#skipping-test-execution

To be honest I was about to say that it is a different thing, but SKIP also implies it needs to be implemented/fixed at some point (same as TODO) and given that this lib is following Gtest naming convention it would be logical to do utest_skip if it is present in gtest (never used it).

**Comment by softael** [comment]
Tried it today - works like a charm! Really appreciate it, also saw your benchmark lib. Definitely going to check it out, since now I am using self made solution in my time-critical app. Thank you for your service! <3

**Comment by sheredom** [comment]
No problem! Honestly both libraries were things I needed myself, and I thought 'hey I wonder if folk would like them?'. Thanks for your kind words!
