### ISSUE TITLE
Allow only compiling implementation details once

### ISSUE THREAD

**Issue by martinfinke** [sheredom/utest.h#107]
Would it be possible to support a macro like `UTEST_IMPLEMENTATION`, similar to how it's done e.g. in the stb libs like [stb_image.h](https://github.com/nothings/stb/blob/master/stb_image.h)?

In utest.h, the declarations and macros would come at the top, and then an `#ifdef UTEST_IMPLEMENTATION`. And after that, all the implementations and internal details.

So as a user, when you normally `#include "utest.h"`, you only get the declarations and macros. And then, in exactly one .c/.cpp file, you only have:

```
#define UTEST_IMPLEMENTATION
#include "utest.h"
```

This time, because `UTEST_IMPLEMENTATION` is defined, utest.h is compiled with all the implementations.

This avoids recompiling most of utest.h over and over while you're writing/changing your test cases. I hope I explained this in a way that's not confusing. And thank you for making utest 🙂 

I would be willing to try this and make a PR, but first wanted to ask if you're interested, because the changes are probably not very diff-friendly 😅

**Comment by sheredom** [comment]
Hey @martinfinke! TL;DR - no I don't want this.

Longer explanation - I **totally** understand why libraries like STB follow that pattern, but for me personally I actually don't like the paradigm. `utest.h` compiles faster than *any other* unit testing library that I've compared it against, and I think giving up a little bit of compile time perf by not having the `_IMPLEMENTATION` macros is worth it to make the library completely trivial to use.
