### ISSUE TITLE
NAN makes test pass

### ISSUE THREAD

**Issue by aganm** [sheredom/utest.h#108]
I have this issue where a NaN makes my test pass:

```
UTEST(test, test)
{
    float test_value = NAN;
    float epsilon = 0.001f;
    EXPECT_NEAR(1.f, test_value, epsilon); // test passes
}
```

Should I check for NaNs everytime I pass a number to a utest macro? Would it make sense for utest to check internally whether values passed to it are NaN before checking the condition, and failing the test if any of the values are NaN?

**Comment by sheredom** [comment]
Huh - NaN should fail there. Lemme have a look.

**Comment by sheredom** [comment]
Can you try #109 for me to double check please?

**Comment by aganm** [comment]
This works!

Naturally since this only patches EXPECT_NEAR and ASSERT_NEAR, NaN will still make all the other test macros pass.

EXPECT_EQ, ASSERT_EQ
EXPECT_NE, ASSERT_NE
EXPECT_LT, ASSERT_LT
EXPECT_LE, ASSERT_LE
EXPECT_GT, ASSERT_GT
EXPECT_GE, ASSERT_GE

For example:

```
UTEST(test, test)
{
    float a = NAN;
    EXPECT_LE(1.f, a); // test passes
}
```

I would think any NaNs passed to any test should make the test fail, since a NaN cannot be used to do any meaningful comparison and will make a test pass silently.

**Comment by sheredom** [comment]
Oh doh! I'll fix, thanks!

**Comment by sheredom** [comment]
Oh damn - now **I remember** what the problem here is - I cannot use anything but `==` for the comparison, because, for it to work in C and C++, and for int and float, I need to use the same operator. Not sure what can be done there actually.

**Comment by sheredom** [comment]
Although actually:

```
[==========] Running 1 test cases.
[ RUN      ] c.nan
/Users/neil/Code/utest.h/test/test.c:257: Failure
  Expected : (1.f) <= (a)
    Actual : 1.000000 vs nan
[  FAILED  ] c.nan (395ns)
```

So this test doesn't pass for me?

```

UTEST(c, nan)
{
    float a = NAN;
    EXPECT_LE(1.f, a); // test passes
}
```

**Comment by aganm** [comment]
Okay, I found the cause of the issue.
With these two tests expected to fail:
```
UTEST(c, near_nan)
{
    float test_value = NAN;
    float epsilon = 0.001f;
    EXPECT_NEAR(1.f, test_value, epsilon);
}

UTEST(c, le_nan)
{
    float a = NAN;
    EXPECT_LE(1.f, a);
}
```
And these different compilation combinations on master branch (both C and C++ have the same results):
| Compiler | Version | Optimization | near_nan | le_nan |
|-----------|--------|-------|------------|--------|
| msvc | x64 v19.latest | /O2 | passes ❌ | fails ✔ |
| clang | x86-64 (trunk) |  -Ofast | passes ❌ | fails ✔ |
| gcc | x86-64 (trunk) | -O3 | passes ❌ | fails ✔ |
| gcc | x86-64 (trunk) | -Ofast | passes ❌ | passes ❌|

And these different compilation combinations with patch #109 (both C and C++ have the same results):

| Compiler | Version | Optimization | near_nan | le_nan |
|-----------|---------|-------|------------|--------|
| msvc | x64 v19.latest | /O2 | fails ✔ | fails ✔ |
| clang | x86-64 (trunk) | -Ofast | fails ✔ | fails ✔ |
| gcc | x86-64 (trunk) | -O3 | fails ✔ | fails ✔ |
| gcc | x86-64 (trunk) |  -Ofast | fails ✔ | passes ❌|

Tested with https://godbolt.org/z/fGYKjqExY.

The only failing test left after #109 is `le_nan` on gcc -Ofast, which I happen to use. Naturally all the other test macros which aren't the NEAR macros also fail, on gcc -Ofast.

I'm not sure if this is a compiler specific issue considering that clang has correct behavior at -Ofast and so does msvc at maximum optimization. What do you think?

**Comment by sheredom** [comment]
Yeah fast math will **totally** make it fail - it allows us to assume no NaNs at all in the numbers (which is why I'd always recommend not using it).

I don't think there is anything I can do if you are using fast here!
