### ISSUE TITLE
Would you be interested in a literate program variant of utest.h?

### ISSUE THREAD

**Issue by yesudeep** [sheredom/utest.h#114]
Namaste,

I've outlined utest.h into an org-mode literate program for personal use, but I'm wondering whether you'd be interested in having utest.h generated by a literate program. Ideally, I wouldn't want to fork it and would prefer it be part of this repository. However, I'm not sure whether you'd be comfortable with Emacs+Org-Mode.

The literate program makes it easier to organize and manage the header file if you can deal with [Emacs+Org-Mode](https://github.com/doomemacs/doomemacs). Please watch https://www.youtube.com/watch?v=wNwBbG5ow6g and let me know.

Thank you!

**Comment by sheredom** [comment]
Its a neat idea - but I don't think I want it no. Thanks for your interest in the project though!
