### ISSUE TITLE
Support for multi-file tests with one single UTEST_MAIN()

### ISSUE THREAD

**Issue by mivinci** [sheredom/utest.h#161]
Say we have `a.c`, `b.c` in which there're several unit tests defined, and a `main.c` in which the `UTEST_MAIN()` is used. But when I compile and link them all together, none of the unit tests got executed.

Such an approach is not supported yet, or there's something I got wrong?

**Comment by sheredom** [comment]
It should be supported yep. Even the tests in the test folder of the project uses that.
