### ISSUE TITLE
test is not run (VS15, Release)

### ISSUE THREAD

**Issue by rnikishyn** [sheredom/utest.h#31]
struct utest_state is empty when run test in Release mode (Visual studio 15). 
 I have printed:
[==========] Running 0 test cases.
[==========] 0 test cases ran.
[  PASSED  ] 0 tests.
Is it ok?

In Debug - all tests are running

**Comment by rnikishyn** [comment]
When I disabled the option "Whole program optimization" - test is running.

**Comment by sheredom** [comment]
I still think you've found an actual thing I should look at fixing, so I'm going to reopen this - thanks for filing it!

**Comment by sheredom** [comment]
Thanks again for the issue - #32 fixes this so you should be able to run with WPO on from now on!
