### ISSUE TITLE
utest.h does not include time.h when compiling on ARM64 Manjaro Linux with Clang

### ISSUE THREAD

**Issue by JoeBobMiles** [sheredom/utest.h#38]
**Problem:** When compiling the unit tests for my project, the Clang build fails with the following errors:
```
In file included from ./main.c:11:
././utest.h:200:19: error: variable has incomplete type 'struct timespec'
  struct timespec ts;
                  ^
././utest.h:200:10: note: forward declaration of 'struct timespec'
  struct timespec ts;
         ^
././utest.h:201:9: error: unknown type name 'clockid_t'
  const clockid_t cid = CLOCK_REALTIME;
        ^
././utest.h:201:25: error: use of undeclared identifier 'CLOCK_REALTIME'
  const clockid_t cid = CLOCK_REALTIME;
                        ^
././utest.h:203:3: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
  clock_gettime(cid, &ts);
  ^
1 warning and 3 errors generated.
```

From some experimentation, I've narrowed the source of the problem down to `time.h` not being included due to `__GLIBC__` and `__GLIBC_MINOR__` becoming undefined somewhere between including C Standard Library headers like `stdio.h` and `utest.h` being included. I unfortunately do not have the experience to know exactly why, nor could I find an immediately obvious reason as to the cause in `utest.h` itself. 

I have not reproduced this on other architectures using Linux, nor with other versions of Linux, but I do know that my code compiled without problem on Windows running on a 64-bit Intel processor.

**Platform:** aarch64 Linux (Manjaro ARM)
**Compiler:** clang 10.0.1

**Steps to reproduce:**
1. Pull latest `utest.h`
2. Create a source file `example.c` with the following contents:
```c
#include <stdio.h>
#include "./utest.h"

UTEST_MAIN();
```
3. Compile `example.c` with using the following command:
```bash
clang -g -std=c99 ./example.c
```

Any thoughts on why this could be happening? I plan to see if I can replicate this on Linux running on a 64-bit Intel processor to rule out the possibility of it being a problem with the POSIX headers used by Manjaro ARM.

**Comment by sheredom** [comment]
Not really sure how to narrow this down to be honest!

You'll notice [here](https://github.com/sheredom/utest.h/blob/master/utest.h#L92) that I include limits.h instead of features.h because of some platform funtimes - could you try doing a `#include <features.h>` there locally and see if that fixes it?

**Comment by JoeBobMiles** [comment]
You know, now I'm even more confused. Looking at that code you pointed out, I also noticed this [`#else` line](https://github.com/sheredom/utest.h/blob/9e4f32de20710bff2ad0b6dd70e9ae14fbe16c11/utest.h#L104) that includes `time.h` when `__GLIBC__` and `__GLIBC_MINOR__` aren't defined. You'd expect that would work, which makes me wonder if either a) `__linux__` isn't being defined (or getting unexpectedly undefined), or b) there's something wrong with `time.h`. The later is probably the most likely, but it seems _extremely_ bizarre that either of those would be the case.

When I'm able, I'll try a few things to narrow this down further, including your suggestion:
* [ ] Include `features.h`.
* [ ] Manually define `__GLIBC__` and `__GLIBC_MINOR__`.
* [ ] Manually define `__linux__`.
* [ ] Compile on x86-64 Linux.

**Comment by JoeBobMiles** [comment]
Well, I didn't get to try any of my experiments. Started over with a fresh clone of `utest.h` and the example source file I gave and it compiled without issue. Realized I had accidentally deleted `utest.h` from my project directory while troubleshooting last night, copied the fresh clone of `utest.h` into my project, compiled the unit tests and got no errors.

Performing a diff of the header I cloned and the `utest.h` already in the source tree shows what when wrong. The version I had been working with was missing these lines (and a few others in `utest_ns()`):
```
#else // Other libc implementations
#include <time.h>
#define UTEST_USE_CLOCKGETTIME
```

Next time I'll make sure to just clone the most recent version before reporting a bug. 😅

**Comment by sheredom** [comment]
@JoeBobMiles don't worry - we've all done that at least once in our lives. No harm done - hope the library is useful to you!
