### ISSUE TITLE
unknown type name __auto_type

### ISSUE THREAD

**Issue by yangxingpping** [sheredom/utest.h#41]
utest.h:396:23: error: unknown type name '__auto_type'

CentOS-7.5.1804 gcc.4.8.5

when I use __typeof__  to replace it,  it seems ok now.

https://stackoverflow.com/questions/62865732/gnu-c-replacement-workaround-for-typeof-auto-type-applied-to-bit-fields

**Comment by sheredom** [comment]
Happy to accept a PR!
