### ISSUE TITLE
uninitialized index member of the utest_test_state_t structure

### ISSUE THREAD

**Issue by DBJDBJ** [sheredom/utest.h#49]
![image](https://user-images.githubusercontent.com/145155/104245827-41f5f400-5465-11eb-9aa0-e24e5852d097.png)

After line #644 the assignment to the index member is what might be mising?

```cpp
    utest_state.tests[index].func = &utest_##SET##_##NAME;       \
    utest_state.tests[index].name = name;                                      \
    utest_state.tests[index].index = index;                                      \
```

**Comment by sheredom** [comment]
Good find! I'll do a PR 😄

**Comment by DBJDBJ** [comment]
### Roger that Sheredom

### Also the line #627 (see above) might be safely removed

![viber_image_2020-06-23_08-35-15](https://user-images.githubusercontent.com/145155/104307188-33442700-54cf-11eb-90c7-c5020196d942.jpg)

**Comment by sheredom** [comment]
I think line 627 needs to stay incase the `UTEST` is in a file all on its own.
