### ISSUE TITLE
Errors with GCC

### ISSUE THREAD

**Issue by friendlyanon** [sheredom/utest.h#51]
One test fails:
```
[ RUN      ] utest_cmdline.filter_with_list
/home/vagrant/code/utest.h/test/main.c:87: Failure
  Expected : undef
    Actual : undef
```

The `type_printers` set also outputs to the console, which is not the case on Windows with MSVC:
```
[ RUN      ] type_printers.stdc
-2147483648-9223372036854775808-9223372036854775808429496729518446744073709551615184467440737095516150.0000000.0000000.000000[       OK ] type_printers.stdc (352203ns)
[ RUN      ] type_printers.cpp
-2147483648-9223372036854775808-9223372036854775808429496729518446744073709551615184467440737095516150.0000000.0000000.000000[       OK ] type_printers.cpp (59254ns)
```

**Comment by sheredom** [comment]
The `type_printers` tests should output to stdout - they use `utest_type_printer` which does fprintf to the output file and printf to stdout.

**Comment by friendlyanon** [comment]
Printing does not happen on Windows with MSVC. See [CI output](https://ci.appveyor.com/project/sheredom/utest-h/builds/37221391/job/br9j5y9a5p9qwdiu).

**Comment by sheredom** [comment]
Those tests don't run on windows it seems.

**Comment by sheredom** [comment]
Can't reproduce sorry.
