### ISSUE TITLE
MSVC : C2733 Repeated linking of external C functions

### ISSUE THREAD

**Issue by ppjxhyyy** [sheredom/utest.h#60]
C2733 : QueryPerformanceCounter & QueryPerformanceFrequency : Cannot overload a function with an external 'C'.

```
# include "utest.h"
# include <windows.h>
```

Env : win7 sp1, vs2019 /std=c++17

**Comment by mirko796** [comment]
Hi there, I've run into same issue today.

It should be fixed in this pull request:
  - https://github.com/sheredom/utest.h/pull/61

Hope it helps...

**Comment by ppjxhyyy** [comment]
@mirko796 I have fixed this issue manually, just to provide a description of the error。 Thanks again
