### ISSUE TITLE
warning C6308 in Visual Studio 2019

### ISSUE THREAD

**Issue by chitalu** [sheredom/utest.h#62]
Hi,

The following warning is being reported in Microsoft Visual Studio Community 2019 (Version 16.6.5):
___

Warning	C6308 'realloc' might return null pointer: assigning null pointer to 'utest_state.tests', which is passed as an argument to 'realloc', will cause the original memory block to be leaked.
___

The warning is reported for every test cases associated with an explicitly-defined fixture.

Can you help to resolve this warning? (For a cleaner build log)

Thanks. 

P.S. We're using utest in MCUT (https://cutdigital.github.io/mcut.github.io/)

**Comment by sheredom** [comment]
I'll have a look aye. I wonder why my testing is not picking this up!

**Comment by chitalu** [comment]
Thank you.
