### ISSUE TITLE
Any way to deploy test statements in function callback?

### ISSUE THREAD

**Issue by zinwalin** [sheredom/utest.h#64]
![image](https://user-images.githubusercontent.com/5416196/115984042-8c941a00-a5d7-11eb-9014-81857cc0c85d.png)

![image](https://user-images.githubusercontent.com/5416196/115984076-b77e6e00-a5d7-11eb-9cf3-33f283294e76.png)

**Comment by sheredom** [comment]
Alas no - there is no way (I'd have to use thread_local variables to get this to work, and there be dragons).
