### ISSUE TITLE
Is utest.h C99 compliant?

### ISSUE THREAD

**Issue by averms** [sheredom/utest.h#81]
I noticed that it compiles fine with `gcc -std=c99 -O3 -Wall` but the `ASSERT_EQ` macro just displays 'undef' when the actual and expected things differ.

**Comment by sheredom** [comment]
It is C99 compat, but with C99 I can't do all the GNU99 tricks I need to do to print the values nicely, so I have to show undef instead https://github.com/sheredom/utest.h/blob/master/utest.h#L479.

All the checks are still performed, a fails is still a fail, but I can't print it out nicely to you the user.
